# Generated by Django 4.1.7 on 2023-06-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_auto_20220807_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='invitation_id',
            field=models.CharField(db_index=True, default=None, max_length=6, unique=True),
        ),
    ]
