# Generated by Django 4.1.7 on 2023-06-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0018_alter_party_invitation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='invitation_id',
            field=models.CharField(db_index=True, default=None, max_length=6, null=True, unique=True),
        ),
    ]
