# Generated by Django 4.1.7 on 2023-06-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0019_alter_party_invitation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='is_invited',
        ),
        migrations.RemoveField(
            model_name='party',
            name='type',
        ),
    ]
