# Generated by Django 4.1.7 on 2023-06-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0022_guest_allergic_alter_guest_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='meal',
            field=models.CharField(blank=True, choices=[('all', 'brak'), ('vege', 'vege'), ('vegan', 'vegan'), ('allergic', 'alergia')], max_length=20, null=True),
        ),
    ]
