# Generated by Django 4.1.7 on 2023-06-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0024_guest_is_allergic_alter_guest_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='plus_one_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
