# Generated by Django 4.1.7 on 2023-06-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0025_guest_plus_one_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='email',
        ),
        migrations.AddField(
            model_name='party',
            name='emailAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='phoneNumber',
            field=models.TextField(blank=True, null=True),
        ),
    ]
