# Generated by Django 4.1.7 on 2023-06-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0026_remove_guest_email_party_emailaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='friSatAccommodation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='party',
            name='satSunAccommodation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='party',
            name='transportation',
            field=models.BooleanField(default=False),
        ),
    ]
