# Generated by Django 4.1.7 on 2023-06-20 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0027_party_frisataccommodation_party_satsunaccommodation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='transportation',
            new_name='transportationNeeded',
        ),
    ]
